### ISSUE TITLE
Only immediate and never in the list

### ISSUE THREAD

**Issue by anidiot** [r-plus/Mesalation#1]
iPhone 6, 9.0.2
I only get immediately and Never! In the grace period list.

**Comment by r-plus** [comment]
How to reproduce?

**Comment by anidiot** [comment]
I have TouchID enabled, so only immediately in the grace period list. Then
I installed mesalation from cydia, respring and went to the list. It only
had immediately and never as options. I didn't do anything special to
reproduce the bug.

iPhone 6, 9.0.2.

**Comment by anidiot** [comment]
https://goo.gl/photos/hWVDuisY4UyLXfju9

**Comment by r-plus** [comment]
outdated issue.

I close this, if you see same bug on newer os version, let me know again.
