### ISSUE TITLE
Mesalation not working anymore after Substitute Update 2.0

### ISSUE THREAD

**Issue by Puschkin-Vodka** [r-plus/Mesalation#5]
iPhone 7plus - iOS 13.5 - Unc0ver 5.3.1

The Tweak worked perfect before updating Substitute to Version 2.0
Now I can't set the grace period to "never".
It's still in the list and it's hooked after tapping on it, but when you get back in the Menu, it's set to "immediately".
All other options like 4h are working.

https://user-images.githubusercontent.com/61467036/104809249-2c2d5980-57ec-11eb-80a8-67aa78a8a160.mp4

**Comment by r-plus** [comment]
thanks for your report.

I will check it too when update this tweak to support iOS 14 even if future substitute version will not resolved.

**Comment by r-plus** [comment]
I just confirmed on iOS 14.1 with unc0ver v6

**Comment by r-plus** [comment]
okey, substitute v2 could not inject to `profiled` daemon by bundleidentifier `com.apple.managedconfiguration.profiled`.
I'll add Executables filter to plist and release it as v0.8.

Thanks.

**Comment by r-plus** [comment]
Cc: @sbingner about substitute.

**Comment by r-plus** [comment]
v0.8 released
